#!/usr/bin/env python3
import argparse
import os
from rs_tools.contrast import contrast
from rs_tools.utils import output_to_window, decompose_filepath, output


def main(args):
    inFile = args.input
    inFile_name = args.input.split("/")[-1].split(".")[-2]

    try:
        inImage = np.array(pix_val_list(Image.open(inFile, "r")))
    except Image.DecompressionBombError:
        inImage = increase_image_size_limit(inFile)

    outImage = contrast(inImage)
    output_to_window(f"{inFile_name}.{args.extension}", outImage, flip=args.flip)

    if args.extension:
        (inDir, filename, _) = decompose_filepath(args.input)

        outDir = f"{inDir}_contrast"
        try:
            os.mkdir(outDir)
        except FileExistsError:
            None

        try:
            output(
                os.path.join(outDir, f"{filename}.{args.extension}"),
                outImage,
            )

        except ValueError:
            print("Not a valid file type")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input", type=str, help="Please provide bands collection path"
    )
    parser.add_argument(
        "--extension",
        type=str,
        help="Please provide the output file extension(Ex. png, jpg, tiff)",
        choices=["png", "jpg", "tiff"],
    )
    parser.add_argument(
        "--flip", type=bool, default=False, help="Flip back to front. True if jp2"
    )

    args = parser.parse_args()
    main(args)
