#!/usr/bin/env python3
from rs_tools.install import install

install()

import argparse
from rs_tools.utils import output, output_to_window
from rs_tools.gaussian import gaussian


def main(args):
    gaussian_img = gaussian(args.input)

    output_name = args.input.split("/")[-1].split(".")[0] + "_gaussian"
    flip = False

    output_to_window(output_name, gaussian_img, flip=flip)

    if args.extension:
        outExtension = "." + args.extension
        outputFile = ".".join(args.input.split(".")[:-1]) + "_gaussian" + outExtension

        try:
            output(outputFile, gaussian_img)
        except ValueError:
            print("Not a valid file type")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input", type=str, help="Please provide path to the input file"
    )
    parser.add_argument(
        "--extension",
        type=str,
        help="Please provide the output file extension(Ex. png, jpg, tiff)",
        choices=["png", "jpg", "tiff"],
    )

    args = parser.parse_args()
    main(args)
