#!/usr/bin/env python3
from rs_tools.install import install

install()

import argparse


def main(args):
    None


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input", type=str, help="Please provide bands collection path"
    )
    parser.add_argument(
        "--products",
        type=str,
        nargs="+",
        help="GLCM products to be generated",
        choices=["entropy", "energy", "contrast", "homogeneity", "dissimilarity"],
    )
    parser.add_argument(
        "--extension",
        type=str,
        help="Please provide the output file extension(Ex. png, jpg, tiff)",
        choices=["png", "jpg", "tiff"],
    )
    parser.add_argument(
        "--flip", type=bool, default=False, help="Flip back to front. True if jp2"
    )

    args = parser.parse_args()
    main(args)
