#!/usr/bin/env python3
from rs_tools.install import install
install()

import argparse
import os
import sys
import re
import csv

from rs_tools.utils import output, output_to_window
from rs_tools.K_Means import generate_K_means, colorNames


def write_stats(pix_location, pix_count, inDir):

    with open(re.sub("$", "_KMeans_stats.csv", inDir), "w", newline="") as statsFile:
        writer = csv.writer(statsFile)
        writer.writerow(["class", "#pixels", "pecentage(%)"])
        for c in pix_location.keys():
            writer.writerow(
                [
                    colorNames[c],
                    len(pix_location[c]),
                    (len(pix_location[c]) / pix_count) * 100,
                ]
            )
        writer.writerow(["total", pix_count, 100])

def print_stats(pix_location, pix_count):
    print("\nResult:")
    for c in pix_location.keys():
        print(
            colorNames[c]
            + ": "
            + str(len(pix_location[c]))
            + "pixels ("
            + str((len(pix_location[c]) / pix_count) * 100)
            + "%)"
        )
    print("\nTotal: " + str(pix_count) + "pixels")

def main(args):

    inDir = args.input

    NIR = args.NIR
    VIS = args.VIS

    try:
        flist = os.listdir(inDir)
        extension = ""
        for f in flist:
            if NIR in f:
                extension = "." + f.split(".")[-1]
            elif VIS in f:
                extension = "." + f.split(".")[-1]
        if extension == "":
            print("The given file path is not valid or does not exist", file=sys.stderr)
            exit(1)

    except FileNotFoundError:
        print("The given file path is not valid or does not exist", file=sys.stderr)
        exit(1)

    pix_val, plot_val, pix_location, pix_count = generate_K_means(
        inDir, NIR, VIS, extension, args.num_iterations, args.num_classes
    )

    print_stats(pix_location, pix_count)

    output_name = args.input.split("/")[-1] + "_KMeans"
    output_to_window(output_name, pix_val)

    plot_output_name = output_name + "_plot"
    output_to_window(plot_output_name, plot_val)

    if args.extension:
        outExtension = "." + args.extension
        classifiedFile = re.sub("$", "_KMeans" + outExtension, inDir)

        try:
            output(classifiedFile, pix_val)
        except ValueError:
            print("Not a valid file type")

        plotFile = re.sub("$", "_KMeans_plot.png", inDir)
        output(plotFile, plot_val)

        write_stats(pix_location, pix_count, inDir)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input", type=str, help="Please provide bands collection path"
    )
    parser.add_argument(
        "--NIR", type=str, help="Please provide the NIR band image file(Ex. B08)"
    )
    parser.add_argument(
        "--VIS", type=str, help="Please provide the visible band image file(Ex. B02)"
    )
    parser.add_argument(
        "--num_iterations", type=str, help="Define the number of iterations"
    )
    parser.add_argument(
        "--num_classes", type=str, help="Define the number of classes from 1 to 7"
    )
    parser.add_argument(
        "--extension",
        type=str,
        help="Please provide the output file extension(Ex. png, jpg, tiff)",
        choices=["png", "jpg", "tiff"],
    )

    args = parser.parse_args()
    main(args)
