#!/usr/bin/env python3
import argparse

def main(args):
    print(args)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument('--input', type=str, help='Please provide bands collection path')
    parser.add_argument('--NIR', type=str, help='Please provide the NIR band image file(Ex. B08)')
    parser.add_argument('--VIS', type=str, help='Please provide the visible band image file(Ex. B02)')
    parser.add_argument('--output',type=str ,help='Please provide the output file extension(Ex. png, jpg, tiff)', choices=['png', 'jpg', 'tiff'])

    args = parser.parse_args()
    main(args)