#!/usr/bin/env python3
from rs_tools.install import install

install()

import argparse
import os
import re

from rs_tools.utils import output, output_to_window
from rs_tools.RGB import extract


def main(args):
    RGB_dict = extract(args.input)

    infile_name = args.input.split("/")[-1]
    band_names = [args.red, args.blue, args.green]

    output_to_window(band_names[0], RGB_dict["R"])
    output_to_window(band_names[1], RGB_dict["G"])
    output_to_window(band_names[2], RGB_dict["B"])

    if args.extension:
        directories = args.input.split("/")[:-1]
        dir_path = "/".join(directories)
        dir_path += "/" + re.sub(".\w+$", "", infile_name)

        try:
            os.mkdir(dir_path)
        except FileExistsError:
            None

        try:
            output(
                os.path.join(dir_path, f"{band_names[0]}.{args.extension}"),
                RGB_dict["R"],
            )
            output(
                os.path.join(dir_path, f"{band_names[1]}.{args.extension}"),
                RGB_dict["G"],
            )
            output(
                os.path.join(dir_path, f"{band_names[2]}.{args.extension}"),
                RGB_dict["B"],
            )
        except ValueError:
            print("Not a valid file type")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input", type=str, help="Please provide bands collection path", required=True
    )
    parser.add_argument(
        "--extension",
        type=str,
        help="Please provide the output file extension(Ex. png, jpg, tiff)",
        choices=["png", "jpg", "tiff"],
    )
    parser.add_argument(
        "-r",
        "--red",
        type=str,
        help="Please provide an 'R' band image file(Ex. B04)",
        required=True,
    )
    parser.add_argument(
        "-g",
        "--green",
        type=str,
        help="Please provide an 'G' band image file(Ex. B03)",
        required=True,
    )
    parser.add_argument(
        "-b",
        "--blue",
        type=str,
        help="Please provide an 'B' band image file(Ex. B02)",
        required=True,
    )

    args = parser.parse_args()
    main(args)
