#!/usr/bin/env python3
from rs_tools.install import install
install()

import argparse

from rs_tools.utils import output, output_to_window
from rs_tools.SOBEL import generate_SOBEL


def main(args):
    SOBEL_Gaussian = generate_SOBEL(args.input)

    output_name = args.input.split("/")[-1].split(".")[0] + "_SOBEL"
    output_to_window(output_name, SOBEL_Gaussian)

    if args.extension:
        outExtension = "." + args.extension
        outputFile = ".".join(args.input.split(".")[:-1]) + "_SOBEL" + outExtension

        try:
            output(outputFile, SOBEL_Gaussian)
        except ValueError:
            print("Not a valid file type")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input", type=str, help="Please provide bands collection path"
    )
    parser.add_argument(
        "--extension",
        type=str,
        help="Please provide the output file extension(Ex. png, jpg, tiff)",
        choices=["png", "jpg", "tiff"],
    )

    args = parser.parse_args()
    main(args)
